[package]
name = "explorers-search"
version = "0.1.0"
edition = "2024"

[dependencies]
explorers-sim = { path = "../explorers-sim" }
explorers-genesis = { path = "../explorers-genesis" }
explorers-genesis-eval = { path = "../explorers-genesis-eval" }
rayon = "1"
rand = "0.9"
rand_chacha = { version = "0.9", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }

[[bin]]
name = "explorers-search"
path = "src/main.rs"
